kind: Service
apiVersion: v1
metadata:
  namespace: final
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
  ports:
  - port: 3306
    targetPort: 3306