kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  labels:
    name: read-pods
  namespace: final
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
  #apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io